embedding_size: 64
hidden_size: 64
seq_length: 10
epoch_size: 20
batch_size: 4
learning_rate: 0.005

input_vocab_path: "./data/input_vocab.txt"
nlu_path: "./data/guotie/nlu.yml"
domain_path: "./data/guotie/domain.yml"
save_dir: "./save/guotie"
