apiVersion: v1
kind: ConfigMap
metadata:
  name: fuzi-nlu
  namespace: fuzi
data:
  suggestNumber: 1
---
apiVersion: v1
kind: Service
metadata:
  name: fuzi-nlu
  namespace: fuzi
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30101
  selector:
     app: fuzi-nlu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzi-nlu
  namespace: fuzi
spec:
  selector:
    matchLabels:
      app: fuzi-nlu
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzi-nlu
    spec:
      containers:
      - name: fuzi-nlu
        image: 192.168.2.101:5000/fuzi-nlu:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: suggestNumber
          valueFrom:
            configMapKeyRef:
              name: fuzi-nlu
              key: suggestNumber
